# Generated by Django 6.0.5 on 2026-06-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['-fecha_pago']},
        ),
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-created_at']},
        ),
    ]
