# Generated by Django 6.0.5 on 2026-06-08 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_matricula_options_alter_resena_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El slug solo puede contener letras, números, espacios, guiones, guiones bajos, comas y puntos.', regex='^[a-zA-Z0-9áéíóúüñÁÉÍÓÚÜÑ\\s\\-_,.]+$')]),
        ),
    ]
